kind: Deployment
apiVersion: apps/v1
metadata:
   name: kirangothe
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: kirangothe
   template:
      metadata:
        labels:
          app: kirangothe
      spec:
       containers:
        - name: kirangothe
          image: kirangothe/ansible-k8s
          imagePullPolicy: Always
          ports:
          - containerPort: 80
