kind: Service                             
apiVersion: v1
metadata:
  name: kirangothe
  labels:
    app: kirangothe
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: kirangothe                    
  type: LoadBalancer                   
